name: Trigger okmkm-blog app Rebuild When Feed Updates

on:
  push:
    branches:
      - main
    paths:
      - "articles/**"
      - "images/**"
  workflow_dispatch:

jobs:
  check-feed-and-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger blog repository rebuild
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: okm321/okmkm-blog
          event-type: zenn-feed-updated
